{{- if .Values.metricsServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "waypoint.fullname" . }}-metrics
  labels:
    {{- include "waypoint.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metricsServer.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "waypoint.selectorLabels" . | nindent 4 }}
{{- end }}
