[package]
name = "waypoint-secrets"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
aws = ["dep:waypoint-secrets-aws"]
google = ["dep:waypoint-secrets-google"]
hashicorp = ["dep:waypoint-secrets-hashicorp"]
azure = ["dep:waypoint-secrets-azure"]
cyberark = ["dep:waypoint-secrets-cyberark"]

[dependencies]
futures-util.workspace = true
waypoint-python-compat.workspace = true
waypoint-secrets-types.workspace = true
waypoint-secrets-aws = { workspace = true, optional = true }
waypoint-secrets-google = { workspace = true, optional = true }
waypoint-secrets-hashicorp = { workspace = true, optional = true }
waypoint-secrets-azure = { workspace = true, optional = true }
waypoint-secrets-cyberark = { workspace = true, optional = true }
waypoint-core-utils.workspace = true
waypoint-http.workspace = true
base64.workspace = true
serde.workspace = true
strum.workspace = true
serde_json.workspace = true
thiserror.workspace = true
reqwest.workspace = true
moka.workspace = true
tokio = { workspace = true, features = ["fs"] }

[dev-dependencies]
waypoint-http = { workspace = true, features = ["test-support"] }
rstest.workspace = true
wiremock.workspace = true
tempfile = "3"
aws-sdk-kms = "1.120.0"
google-cloud-kms-v1 = "1.14.0"
google-cloud-auth.workspace = true
