[package]
name = "waypoint-inference"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
waypoint-cache.workspace = true
waypoint-cache-response.workspace = true
waypoint-framer.workspace = true
tokio-util = { version = "0.7", features = ["codec"] }
waypoint-secrets.workspace = true
waypoint-core-utils.workspace = true
waypoint-host.workspace = true
bytes.workspace = true
futures-util.workspace = true
waypoint-auth = { workspace = true, features = ["aws", "azure", "gcp"] }
waypoint-http.workspace = true
waypoint-llms.workspace = true
waypoint-tracing.workspace = true
tracing.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["preserve_order"] }
tokio = { workspace = true, features = ["sync"] }
thiserror.workspace = true
time.workspace = true
url.workspace = true

[dev-dependencies]
waypoint-cache-memory.workspace = true
waypoint-http = { workspace = true, features = ["test-support"] }
waypoint-llms = { workspace = true, features = ["test-support"] }
rstest.workspace = true
