[package]
name = "waypoint-python-bridge"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "_native"
crate-type = ["cdylib"]

[features]
default = ["abi3", "fast", "huggingface", "tiktoken"]
abi3 = ["pyo3/abi3-py310"]
extension-module = ["pyo3/extension-module"]
panic-test = []
fast = ["waypoint-token-counter/fast"]
huggingface = ["waypoint-token-counter/huggingface"]
tiktoken = ["waypoint-token-counter/tiktoken"]

[dependencies]
fancy-regex.workspace = true
waypoint-tracing.workspace = true
waypoint-traces.workspace = true
waypoint-traces-cache.workspace = true
waypoint-traces-clickhouse.workspace = true
waypoint-storage-clickhouse.workspace = true
waypoint-host.workspace = true
bytes.workspace = true
futures-util.workspace = true
waypoint-cache.workspace = true
waypoint-cache-memory.workspace = true
waypoint-cache-redis.workspace = true
waypoint-cache-response.workspace = true
serde.workspace = true
waypoint-auth.workspace = true
waypoint-auth-aws.workspace = true
waypoint-callbacks-legacy-python.workspace = true
waypoint-inference.workspace = true
waypoint-inference-transcription.workspace = true
waypoint-inference-responses.workspace = true
waypoint-inference-messages.workspace = true
waypoint-inference-chat.workspace = true
waypoint-inference-ocr.workspace = true
waypoint-core-utils.workspace = true
waypoint-http.workspace = true
waypoint-llms.workspace = true
waypoint-secrets = { workspace = true, features = ["aws", "azure", "google", "hashicorp", "cyberark"] }
waypoint-secrets-types.workspace = true
waypoint-llms-types.workspace = true
waypoint-host-python.workspace = true
waypoint-token-counter = { path = "../token-counter", default-features = false }
pyo3.workspace = true
prost.workspace = true
pyo3-async-runtimes.workspace = true
reqwest.workspace = true
redis = { version = "1.7.0", features = ["tls-rustls"] }
serde_json.workspace = true
strum.workspace = true
veil.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "sync"] }

[dev-dependencies]
tracing.workspace = true
waypoint-http = { workspace = true, features = ["test-support"] }
waypoint-secrets-aws.workspace = true
serde.workspace = true
serde_with.workspace = true
criterion.workspace = true
futures-util.workspace = true
rstest.workspace = true
sqlx = { workspace = true, features = ["migrate"] }
tokio-tungstenite.workspace = true
wiremock.workspace = true
aws-sdk-secretsmanager = "1.117.0"

[[bench]]
name = "serialization"
harness = false
